//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.Device.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.Device.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Read failed.
        ///{1}.
        /// </summary>
        internal static string _0ReadFailed1 {
            get {
                return ResourceManager.GetString("_0ReadFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Medias.
        /// </summary>
        internal static string AllMedias {
            get {
                return ResourceManager.GetString("AllMedias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is unknown..
        /// </summary>
        internal static string CategoryNameIsUnknown {
            get {
                return ResourceManager.GetString("CategoryNameIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        internal static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find unpacked device file.
        /// </summary>
        internal static string CouldNotFindUnpackedDeviceFile {
            get {
                return ResourceManager.GetString("CouldNotFindUnpackedDeviceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataIOSource target is unknown..
        /// </summary>
        internal static string DataIOSourceTargetIsUnknown {
            get {
                return ResourceManager.GetString("DataIOSourceTargetIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device file does not exist in the packet..
        /// </summary>
        internal static string DeviceFileDoesNotExistInThePacket {
            get {
                return ResourceManager.GetString("DeviceFileDoesNotExistInThePacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device installation failed.
        /// </summary>
        internal static string DeviceInstallationFailed {
            get {
                return ResourceManager.GetString("DeviceInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type is not preset..
        /// </summary>
        internal static string DeviceTypeIsNotPreset {
            get {
                return ResourceManager.GetString("DeviceTypeIsNotPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace existing device?.
        /// </summary>
        internal static string DoYouWantToReplaceExistingDevice {
            get {
                return ResourceManager.GetString("DoYouWantToReplaceExistingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ended..
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry read type is invalid..
        /// </summary>
        internal static string EntryReadTypeIsInvalid {
            get {
                return ResourceManager.GetString("EntryReadTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute .
        /// </summary>
        internal static string FailedToExecute {
            get {
                return ResourceManager.GetString("FailedToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Add-In &apos;{0}&apos;
        ///{1}.
        /// </summary>
        internal static string FailedToLoadAddIn01 {
            get {
                return ResourceManager.GetString("FailedToLoadAddIn01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Load file: .
        /// </summary>
        internal static string FailedToLoadFile {
            get {
                return ResourceManager.GetString("FailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed to validate table .
        /// </summary>
        internal static string FiledToValidateTable {
            get {
                return ResourceManager.GetString("FiledToValidateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindItemByID failed. Search ID can&apos;t be Zero..
        /// </summary>
        internal static string FindItemByIDFailedSearchIDCanTBeZero {
            get {
                return ResourceManager.GetString("FindItemByIDFailedSearchIDCanTBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Acknowledge message: .
        /// </summary>
        internal static string InvalidAcknowledgeMessage {
            get {
                return ResourceManager.GetString("InvalidAcknowledgeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Gurux Device template ID..
        /// </summary>
        internal static string InvalidGuruxDeviceTemplateID {
            get {
                return ResourceManager.GetString("InvalidGuruxDeviceTemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GXCommunicationAttribute..
        /// </summary>
        internal static string InvalidGXCommunicationAttribute {
            get {
                return ResourceManager.GetString("InvalidGXCommunicationAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media state..
        /// </summary>
        internal static string InvalidMediaState {
            get {
                return ResourceManager.GetString("InvalidMediaState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PacketHandlerType..
        /// </summary>
        internal static string InvalidPacketHandlerType {
            get {
                return ResourceManager.GetString("InvalidPacketHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parent..
        /// </summary>
        internal static string InvalidParent {
            get {
                return ResourceManager.GetString("InvalidParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid protocol AddIn .
        /// </summary>
        internal static string InvalidProtocolAddIn {
            get {
                return ResourceManager.GetString("InvalidProtocolAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start type..
        /// </summary>
        internal static string InvalidStartType {
            get {
                return ResourceManager.GetString("InvalidStartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value. Forced preset value not found..
        /// </summary>
        internal static string InvalidValueForcedPresetValueNotFound {
            get {
                return ResourceManager.GetString("InvalidValueForcedPresetValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value. Forceed preset value not found..
        /// </summary>
        internal static string InvalidValueForceedPresetValueNotFound {
            get {
                return ResourceManager.GetString("InvalidValueForceedPresetValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It already exists..
        /// </summary>
        internal static string ItAlreadyExists {
            get {
                return ResourceManager.GetString("ItAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It&apos;s Index already exists in .
        /// </summary>
        internal static string ItSIndexAlreadyExistsIn {
            get {
                return ResourceManager.GetString("ItSIndexAlreadyExistsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media properties.
        /// </summary>
        internal static string MediaProperties {
            get {
                return ResourceManager.GetString("MediaProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Protocols Found..
        /// </summary>
        internal static string NoProtocolsFound {
            get {
                return ResourceManager.GetString("NoProtocolsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parentless device monitoring is not allowed..
        /// </summary>
        internal static string ParentlessDeviceMonitoringIsNotAllowed {
            get {
                return ResourceManager.GetString("ParentlessDeviceMonitoringIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parentless schedule can&apos;t be activated..
        /// </summary>
        internal static string ParentlessScheduleCanTBeActivated {
            get {
                return ResourceManager.GetString("ParentlessScheduleCanTBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name can&apos;t be empty..
        /// </summary>
        internal static string PropertyNameCanTBeEmpty {
            get {
                return ResourceManager.GetString("PropertyNameCanTBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name is unknown..
        /// </summary>
        internal static string PropertyNameIsUnknown {
            get {
                return ResourceManager.GetString("PropertyNameIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Schedule ended..
        /// </summary>
        internal static string ScheduleEnded {
            get {
                return ResourceManager.GetString("ScheduleEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Schedule started..
        /// </summary>
        internal static string ScheduleStarted {
            get {
                return ResourceManager.GetString("ScheduleStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send failed..
        /// </summary>
        internal static string SendFailed {
            get {
                return ResourceManager.GetString("SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  started..
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name can&apos;t be empty..
        /// </summary>
        internal static string TableNameCanTBeEmpty {
            get {
                return ResourceManager.GetString("TableNameCanTBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is unknown..
        /// </summary>
        internal static string TableNameIsUnknown {
            get {
                return ResourceManager.GetString("TableNameIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the category can&apos;t be empty..
        /// </summary>
        internal static string TheNameOfTheCategoryCanTBeEmpty {
            get {
                return ResourceManager.GetString("TheNameOfTheCategoryCanTBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout occurred..
        /// </summary>
        internal static string TimeoutOccurred {
            get {
                return ResourceManager.GetString("TimeoutOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is already in progress..
        /// </summary>
        internal static string TransactionIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("TransactionIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data in exported file. {0}.
        /// </summary>
        internal static string UnknownDataInExportedFile0 {
            get {
                return ResourceManager.GetString("UnknownDataInExportedFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device profile.
        /// </summary>
        internal static string UnknownDeviceProfile {
            get {
                return ResourceManager.GetString("UnknownDeviceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown target..
        /// </summary>
        internal static string UnknownTarget {
            get {
                return ResourceManager.GetString("UnknownTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval is not set..
        /// </summary>
        internal static string UpdateIntervalIsNotSet {
            get {
                return ResourceManager.GetString("UpdateIntervalIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version comparisation failed:
        ///.
        /// </summary>
        internal static string VersionComparisationFailed {
            get {
                return ResourceManager.GetString("VersionComparisationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait {0} ms. before next packet is send..
        /// </summary>
        internal static string Wait0MsBeforeNextPacketIsSend {
            get {
                return ResourceManager.GetString("Wait0MsBeforeNextPacketIsSend", resourceCulture);
            }
        }
    }
}
